### PR TITLE
DefaultValueObjectWriter should populate oneof message field

### LINKED ISSUE #2418: json serialization option always_print_primitive_fields does not work across oneof
Primitive fields are not printed if they are inside a member inside oneof.

% protoc --version
libprotoc 3.1.0

Linux

Given
```proto
syntax="proto3";
message hei {
        int32 x=1;
}
message hallo {
        oneof joda {
        hei a=1;
     }
}
```
AND

```c++
#include "t.pb.h"
#include <google/protobuf/util/json_util.h>
#include <iostream>

using namespace google::protobuf::util;
using namespace std;

int main() {
    hei x;
    hallo y;
    *y.mutable_a()= x;
    string str;
    JsonOptions options;
    options.add_whitespace= true;
    options.always_print_primitive_fields= true;
    MessageToJsonString(y, &str, options);
    MessageToJsonString(y.a(), &str, options);
    cout << str << endl;
}
```

The output is:
{
 "a": {}
}
{
 "x": 0
}

### PR DESCRIPTION
**Pull request by anandolee**
fixes #2418

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

File: src/google/protobuf/util/internal/default_value_objectwriter.cc [hunk 1]
```diff
@@ -363,8 +363,9 @@ void DefaultValueObjectWriter::Node::PopulateChildren(
     }
 
     // If oneof_index() != 0, the child field is part of a "oneof", which means
-    // the child field is optional and we shouldn't populate its default value.
-    if (field.oneof_index() != 0) continue;
+    // the child field is optional and we shouldn't populate its default
+    // primitive value.
+    if (field.oneof_index() != 0 && kind == PRIMITIVE) continue;
```
Comment (xfxyjwf) [inline src/google/protobuf/util/internal/default_value_objectwriter.cc]: Why is this needed to fix the issue? I thought DefaultValueObjectWriter should just ignore all oneof fields because these fields have field presence.

Comment (anandolee) [inline src/google/protobuf/util/internal/default_value_objectwriter.cc]: Need to create the child node for message field so DefaultValueObjectWriter can go over the tree

**Comment by xfxyjwf** [comment]
retest this please

**Comment by anandolee** [comment]
Build failure "php_all.php_all" is not related
