### PR TITLE
Fix for issue 283: JSON handler cleanup typo causing segfault.

### LINKED ISSUE #283: Ruby: encoding messages w/ message fields as JSON segfaults
We're currently testing w/ google-protobuf-3.0.0.alpha.2.0 (this appears to be the latest released version on rubygems.org) alongside grpc's ruby bindings.

Given a couple messages, defined as:

``` proto
syntax = "proto3";
package = example;

message Foo {
       string foo = 1;
}

message Bar {
       string bar = 1;
       Foo foo = 2;
}
```

And some Ruby attempting to encode these messages as JSON:

``` ruby
# this does not blow up
foo = Example::Foo.new(foo: "this is okay")
Example::Foo.encode_json(foo)

# this very much blows up
Example::Bar.encode_json(Example::Bar.new)

# this also blows up
bar = Example::Bar.new(bar: "this is not okay")
Example::Bar.encode_json(bar)

# this blows up as well
foo = Example::Foo.new(foo: "womp womp")
bar = Example::Bar.new(bar: "this is not okay", foo: foo)
Example::Bar.encode_json(bar)
```

The failing examples as listed above all result in the same segmentation fault inside protobuf_c:

```
/usr/local/bundle/bin/rspec: [BUG] Segmentation fault at 0x0000000000001c
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0001 p:0000 s:0002 E:001d98 TOP    [FINISH]


-- C level backtrace information -------------------------------------------
ruby(+0x1823bc) [0x7f375e46e3bc]
ruby(+0x1f4343) [0x7f375e4e0343]
ruby(rb_bug+0xb3) [0x7f375e4e1543]
ruby(+0xf923f) [0x7f375e3e523f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7f375debb8d0]
/usr/local/bundle/extensions/x86_64-linux/2.1.0-static/google-protobuf-3.0.0.alpha.2.0/google/protobuf_c.so(upb_refcounted_unref+0) [0x7f3758783e90] upb.c:5781
/usr/local/bundle/extensions/x86_64-linux/2.1.0-static/google-protobuf-3.0.0.alpha.2.0/google/protobuf_c.so(Descriptor_free+0x67) [0x7f3758770c87] defs.c:253
ruby(+0x3b0df) [0x7f375e3270df]
ruby(rb_gc_call_finalizer_at_exit+0x2d9) [0x7f375e32d1d9]
ruby(ruby_cleanup+0x3df) [0x7f375e31211f]
ruby(ruby_run_node+0x36) [0x7f375e312486]
ruby(+0x226cb) [0x7f375e30e6cb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f375d3e8b45] upb.h:6243
ruby(+0x226f9) [0x7f375e30e6f9]
```

### PR DESCRIPTION
**Pull request by cfallin**
Fixes #283.

Also bumped Gem version so that we can release a fixed version to RubyGems.

### CODE REVIEW

**Comment by cfallin** [comment]
@haberman or @pherl to review.

File: ruby/ext/google/protobuf_c/defs.c [hunk 1]
```diff
@@ -250,7 +250,7 @@ void Descriptor_free(void* _self) {
                        &self->pb_serialize_handlers);
   }
   if (self->json_serialize_handlers) {
-    upb_handlers_unref(self->pb_serialize_handlers,
+    upb_handlers_unref(self->json_serialize_handlers,
```
Comment (haberman) [inline ruby/ext/google/protobuf_c/defs.c]: I would have expected a UPB_DEBUG_REFS build to catch this. I don't know if there's any easy way to do this, but if there was any way to test without NDEBUG defined, that would probably be a good idea.
